import Head from 'next/head'
import {BsFillMoonStarsFill,BsGithub,BsLinkedin,BsTwitter} from 'react-icons/bs'
import Image from 'next/image'
import jasjot from '../../public/jasjot.jpg'
import disp from '../../public/disp.jpg'
import frontend from '../../public/front-end.jpg'
import api from '../../public/api.png'
import others from '../../public/others.jpg'
import project from '../../public/project.png'
import Link from 'next/link'
import { getStorage, ref, getDownloadURL } from "firebase/storage";
import storage from 'utils/firebase'
import { useEffect, useState } from 'react'
import empporj from '../../public/empporj.png'
import proj2 from '../../public/proj2.png'


export default function Home() {
  const [darkMode,setDarkMode]=useState(false)
const [resume,setResume]=useState(null)

const handleClick=()=>{
  const aTag=document.createElement('a')
   aTag.href=resume;
   aTag.setAttribute('download','Resume.pdf')
   document.body.appendChild(aTag)
   aTag.click();
   aTag.remove();
}

  useEffect(()=>{
    const storage=getStorage();
   const Ref=ref(storage,'Resume.pdf')

   getDownloadURL(Ref).then((url)=>{
    setResume(url)
   })
  },[])
 console.log(resume)
  return (
    <div className={darkMode?'dark':''}>
      <Head>
        <title>Jasjot Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40"  >
        <section>
       <nav className="flex p-5 justify-between mb-12 dark:text-white ">
        <h1 className=" font-serif text-xl items-center">Developed by Jasjot</h1>
        <ul className=" flex justify-between items-center">
          <li className=" text-xl cursor-pointer"><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} /></li>
        
          <li className=" ml-4 bg-cyan-500 p-2 rounded-l cursor-pointer" onClick={handleClick}>Resume</li>
          
        </ul>
       </nav>
       <div className="flex justify-center text-center flex-col ">
        <h2 className="text-5xl p-2 text-cyan-500 font-medium dark:text-cyan-400 ">Jasjot Singh</h2>
        <h3 className="text-2xl p-2 md:text-3xl dark:text-white">Full stack developer</h3>
        <p className="text-xl  leading-10 p-5 md:text-xl max-w-xl mx-auto dark:text-gray-200">	Welcome to my portfolio website!
           I am a dedicated full stack developer with a passion for technology and problem-solving. Currently, I am part 
           of the FDM IDB pod, where I contribute to developing a cutting-edge banking app using the MERN stack, 
           including developing a REST API using Node.js. With deep knowledge in Java and Spring Boot, I bring a comprehensive
            skill set to every project. My experience also includes a year as a front-end developer at Web Allures, where I 
            honed my skills in creating dynamic and user-friendly web applications. Additionally, I have conducted numerous 
            technical presentations for clients like Wawanesa Insurance, TD Bank, and Intact, showcasing the latest advancements
             in our IDB app using the latest tools. Explore my portfolio to see the projects I've worked on and the skills I
              bring to the table.</p>
       <div className="text-5xl flex justify-center  gap-16 p-3 text-gray-800 dark:text-gray-400">
        <Link href="https://github.com/BotJB">
       <BsGithub className=" cursor-pointer" />
       </Link>
       <Link href="https://www.linkedin.com/in/jasjot-singh-4b7253260/">
       <BsLinkedin className=" cursor-pointer" />
       </Link>
       <BsTwitter className=" cursor-pointer"/>
       </div>
       </div>
       <div className="mx-auto bg-gradient-to-b from-cyan-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96  ">
              <Image src={disp} layout="fill" objectFit="cover" />
            </div>
       </section>
       <section>
        <h3 className='text-2xl p-2 text-center dark:text-white '>Services I can offer</h3>
        <p className='text-xl  leading-10 p-5  dark:text-gray-200'>During my graduation, web development courses, and personal
           projects, I have developed a diverse skill set. I am experienced with core front-end technologies such as HTML, CSS,
            and JavaScript, and I have worked extensively with React and Next.js. Additionally, I am proficient in back-end 
            development using Node.js, Java, and Spring Boot, and I am familiar with REST API architecture. I also have a deep
             understanding of data structures and algorithms. My journey includes working as a front-end developer at Web Allures 
             for a year and currently contributing to the FDM IDB pod, where I work on a banking app using the MERN stack.
           </p>
           <div className=' lg:flex gap-10 '>
            <div className='text-center   shadow-lg p-10 rounded-xl my-10 mx-10 flex-1  dark:bg-white'>
              <div className=' mx-auto mb-5 bg-gradient-to-b from-cyan-500 rounded-full w-10 h-10 relative overflow-hidden mt-10 md:h-15 md:w-15'>
            <Image className=' mx-auto'  src={frontend} alt="front-end-logo" />
            </div>
            <h3 className=' text-xl pb-4 '>Front End Tools</h3>
           <ul className=' text-gray-700 text-lg'>
            <li>HTML, CSS, Javascript</li>
            <li>React,Redux,Next JS</li>
            <li>Angular</li>
            <li>Testing Using Jest,React testing library</li>
           </ul>
            </div>
            <div className='text-center   shadow-lg p-10 rounded-xl mx-10 my-10 flex-1  dark:bg-white'>
              <div className=' mx-auto mb-5 bg-gradient-to-b from-cyan-500 rounded-full w-10 h-10 relative overflow-hidden mt-10 md:h-15 md:w-15'>
            <Image className=' mx-auto'  src={api} alt="front-end-logo" />
            </div>
            <h3 className=' text-xl pb-4 '>Back End and Database Tools</h3>
           <ul className=' text-gray-700 text-lg'>
            <li>Node Js, Express JS</li>
            <li>Java,Spring Boot</li>
            <li>Sql and NoSql Databases</li>
            <li>REST API and Microservices</li>
           </ul>
            </div>
            <div className='text-center   shadow-lg p-10 rounded-xl my-10 mx-10 flex-1  dark:bg-white'>
              <div className=' mx-auto mb-5 bg-gradient-to-b from-cyan-500 rounded-full w-10 h-10 relative overflow-hidden mt-10 md:h-15 md:w-15'>
            <Image className=' mx-auto'  src={others} alt="front-end-logo" />
            </div> 
            <h3 className=' text-xl pb-4'>Other Tools</h3>
           <ul className=' text-gray-700 text-lg'>
            <li>Github</li>
            <li>Trello,Jira</li>
            <li>Postman,Swagger</li>
            <li>Agile and Waterfall development methods</li>
           </ul>
            </div>
           </div>

    </section>
    <section>
      <h1 className=' text-2xl text-center m-5 lg:text-5xl dark:text-white'>Projects</h1>
      <div className=' shadow-lg m-9 items-center'>
        <h3 className=' text-lg text-center lg:text-2xl dark:text-gray-200'>Employee Management System</h3>
        <p className='text-lg m-8 dark:text-gray-200'>This project is built using the MERN stack, utilizing React for the front end and Node.js with Express.js for the backend, and MongoDB as the database. It is fully responsive, thanks to React Bootstrap. To try it out click on the image </p>
        <h5 className="text-xl font-semibold mb-4 pl-10">Key features</h5>
<ul className="list-disc pl-10 space-y-2 mb-5">
  <li className="text-sm text-gray-700">Built using MVC architecture</li>
  <li className="text-sm text-gray-700">Add, edit, delete, and filter employee data</li>
  <li className="text-sm text-gray-700">Export employee records in CSV format</li>
  <li className="text-sm text-gray-700">Meaningful messages and error handling using React Toastify</li>
</ul>
        <Link href="https://668d5535dfc64487c4b8d9cf--glistening-meringue-1a9d85.netlify.app/">
        <Image src={empporj} className='mx-auto' />
        </Link>
        
        <h3 className=' text-lg text-center px-2 lg:text-2xl dark:text-gray-200 '>Online TODO App</h3>
        <p className='text-lg m-8 dark:text-gray-200'>This project uses the MERN stack. To use this app, users need to either sign up or log in using their credentials. It uses session-based authentication. Users can make new tasks, edit the progress of old tasks, change the priority of tasks, delete tasks, and sign out when done. TO try it out click ont he image</p>
        <h5 className="text-xl font-semibold mb-4 pl-10">Key features</h5>
<ul className="list-disc pl-10 space-y-2 mb-5">
  <li className="text-sm text-gray-700">Built using MVC architecture</li>
  <li className="text-sm text-gray-700">Built using the MERN stack</li>
  <li className="text-sm text-gray-700">Session-based authentication for secure access</li>
  <li className="text-sm text-gray-700">Change the priority of tasks using sliders</li>
  </ul>
  <h5 className="text-xl font-semibold mb-4 pl-10">To try it out</h5>
<ul className="list-disc pl-10 space-y-2 mb-5">
  <li className="text-sm text-gray-700">Email: jj@hotmail.com</li>
  <li className="text-sm text-gray-700">Password: Password@9</li>
  <li className="text-sm text-gray-700">Or signup using your own email</li>
  </ul>
        <Link href="https://668d6ad98c3d50a6c966247c--vermillion-starship-034ece.netlify.app/">
        <Image src={proj2} className='mx-auto' />
        </Link>
        
      </div>
    </section>

      

      
      </main>
    </div>
  )
}
